import dayjs from 'dayjs';

export const taskList = [
    {
        taskId: 1,
        taskTitle: 'Fix login bug',
        description: 'Resolve issue with user login not redirecting properly.',
        remainderAt: '10:00 AM, Tomorrow',
        isCompleted: false,
    },
    {
        taskId: 2,
        taskTitle: 'Update README',
        description: 'Add setup instructions to the project README file.',
        remainderAt: '04:00 PM, Today',
        isCompleted: true,
    },
    {
        taskId: 3,
        taskTitle: 'Implement user roles',
        description: 'Add support for admin and regular user roles.',
        remainderAt: '11:30 AM, Friday',
        isCompleted: false,
    },
    {
        taskId: 4,
        taskTitle: 'Refactor codebase',
        description:
            'Clean and refactor utility functions for better performance.',
        remainderAt: '01:00 PM, Monday',
        isCompleted: false,
    },
    {
        taskId: 5,
        taskTitle: 'Design homepage',
        description: 'Create wireframes for the new landing page.',
        remainderAt: '03:00 PM, Saturday',
        isCompleted: true,
    },
    {
        taskId: 6,
        taskTitle: 'Push to GitHub',
        description: 'Ensure latest changes are committed and pushed.',
        remainderAt: '06:00 PM, Today',
        isCompleted: false,
    },
    {
        taskId: 7,
        taskTitle: 'Set up CI/CD',
        description: 'Integrate GitHub Actions for automated testing.',
        remainderAt: '09:00 AM, Thursday',
        isCompleted: false,
    },
    {
        taskId: 8,
        taskTitle: 'Write unit tests',
        description: 'Add test cases for auth and profile modules.',
        remainderAt: '02:00 PM, Tomorrow',
        isCompleted: false,
    },
    {
        taskId: 9,
        taskTitle: 'Team meeting',
        description: 'Weekly sync-up with the development team.',
        remainderAt: '10:30 AM, Wednesday',
        isCompleted: true,
    },
    {
        taskId: 10,
        taskTitle: 'Review pull requests',
        description: 'Go through the list of pending PRs and provide feedback.',
        remainderAt: '05:00 PM, Today',
        isCompleted: false,
    },
    {
        taskId: 11,
        taskTitle: 'Optimize images',
        description: 'Compress large images on the site for faster load times.',
        remainderAt: '12:00 PM, Friday',
        isCompleted: false,
    },
    {
        taskId: 12,
        taskTitle: 'Fix mobile layout',
        description: 'Correct layout issues on small screen devices.',
        remainderAt: '08:00 AM, Monday',
        isCompleted: true,
    },
    {
        taskId: 13,
        taskTitle: 'Prepare demo',
        description: 'Finalize the feature demo for stakeholders.',
        remainderAt: '03:30 PM, Thursday',
        isCompleted: false,
    },
    {
        taskId: 14,
        taskTitle: 'Create banner',
        description: 'Design promotional banner for product launch.',
        remainderAt: '01:30 PM, Saturday',
        isCompleted: false,
    },
    {
        taskId: 15,
        taskTitle: 'Update dependencies',
        description: 'Upgrade npm packages to the latest stable versions.',
        remainderAt: '07:00 PM, Today',
        isCompleted: false,
    },
    {
        taskId: 16,
        taskTitle: 'Analyze user feedback',
        description:
            'Go through recent feedback to identify areas of improvement.',
        remainderAt: '04:30 PM, Tuesday',
        isCompleted: true,
    },
    {
        taskId: 17,
        taskTitle: 'Backup database',
        description: 'Perform scheduled DB backup for disaster recovery.',
        remainderAt: '12:30 PM, Tomorrow',
        isCompleted: false,
    },
    {
        taskId: 18,
        taskTitle: 'Fix 404 errors',
        description: 'Identify and fix broken links on the website.',
        remainderAt: '10:15 AM, Wednesday',
        isCompleted: true,
    },
    {
        taskId: 19,
        taskTitle: 'Update contact form',
        description: 'Add new fields and validations to the contact form.',
        remainderAt: '11:45 AM, Monday',
        isCompleted: false,
    },
    {
        taskId: 20,
        taskTitle: 'Schedule deployment',
        description: 'Plan and communicate next release deployment date.',
        remainderAt: '09:45 AM, Friday',
        isCompleted: false,
    },
];
export const projectsArray = [
    {
        projectTitle: 'Project Alpha',
        progress: 20,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(5, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 10,
        priority: 'high',
    },
    {
        projectTitle: 'NodeJS API',
        progress: 65,
        startDate: dayjs().subtract(2, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(3, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 8,
        priority: 'medium',
    },
    {
        projectTitle: 'React Frontend',
        progress: 90,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(1, 'week').format('DD MMMM, YYYY'),
        noOfTasks: 12,
        priority: 'low',
    },
    {
        projectTitle: 'MongoDB Schema',
        progress: 50,
        startDate: dayjs().subtract(3, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(4, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 7,
        priority: 'medium',
    },
    {
        projectTitle: 'Admin Panel',
        progress: 30,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(6, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 9,
        priority: 'high',
    },
    {
        projectTitle: 'UI/UX Design',
        progress: 10,
        startDate: dayjs().add(1, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(10, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 15,
        priority: 'high',
    },
    {
        projectTitle: 'Express Backend',
        progress: 55,
        startDate: dayjs().subtract(1, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(2, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 11,
        priority: 'medium',
    },
    {
        projectTitle: 'Authentication',
        progress: 75,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(5, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 6,
        priority: 'low',
    },
    {
        projectTitle: 'Payment Gateway',
        progress: 25,
        startDate: dayjs().add(2, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(12, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 13,
        priority: 'high',
    },
    {
        projectTitle: 'E-Commerce',
        progress: 85,
        startDate: dayjs().subtract(2, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(5, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 18,
        priority: 'medium',
    },
    {
        projectTitle: 'Inventory System',
        progress: 40,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(3, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 14,
        priority: 'low',
    },
    {
        projectTitle: 'Chat Integration',
        progress: 60,
        startDate: dayjs().subtract(1, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(6, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 10,
        priority: 'medium',
    },
    {
        projectTitle: 'Bug Tracker',
        progress: 95,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(1, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 5,
        priority: 'low',
    },
    {
        projectTitle: 'Admin Dashboard',
        progress: 70,
        startDate: dayjs().subtract(3, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(4, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 9,
        priority: 'high',
    },
    {
        projectTitle: 'CMS Development',
        progress: 35,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(9, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 7,
        priority: 'medium',
    },
    {
        projectTitle: 'Analytics Setup',
        progress: 50,
        startDate: dayjs().subtract(2, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(8, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 6,
        priority: 'high',
    },
    {
        projectTitle: 'Social Login',
        progress: 15,
        startDate: dayjs().add(3, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(10, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 8,
        priority: 'medium',
    },
    {
        projectTitle: 'SEO Optimization',
        progress: 45,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(7, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 5,
        priority: 'low',
    },
    {
        projectTitle: 'Notification System',
        progress: 88,
        startDate: dayjs().subtract(1, 'day').format('DD MMMM, YYYY'),
        endDate: dayjs().add(4, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 11,
        priority: 'high',
    },
    {
        projectTitle: 'User Roles Setup',
        progress: 65,
        startDate: dayjs().format('DD MMMM, YYYY'),
        endDate: dayjs().add(6, 'day').format('DD MMMM, YYYY'),
        noOfTasks: 7,
        priority: 'medium',
    },
];
